version: '2'
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/html:/var/www/html
      - ./nginx/.htpasswd:/var/www/.htpasswd
    env_file:
      - ./shared.env
    privileged: true
    network_mode: host 

  htpass:
    build:
      context: ./nginx
    volumes:
      - ./nginx/.htpasswd:/var/www/.htpasswd
      - ./users.txt:/users.txt
    environment:
      - USERS_FILE=/users.txt

  knocker:
    build:
      context: ./knocker
    privileged: true
    ports: 
      - "8080:8080"
    volumes:
      - ./knocker/labean.conf:/etc/labean.conf

  openconnect:
    build:
      context: ./openconnect
    ports:
      - "4443:443"
    privileged: true
    volumes:
      - ./users.txt:/etc/ocserv/users.txt

