version: '2'
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/html:/var/www/html
      - ./nginx/.htpasswd:/var/www/.htpasswd
    env_file:
      - ./shared.env
    ports:
      - "443:443"
    expose:
      - "443"
    privileged: true

  htpass:
    build:
      context: ./nginx
    volumes:
      - ./nginx/.htpasswd:/var/www/.htpasswd
      - ./users.txt:/users.txt
    environment:
      - USERS_FILE=/users.txt

  knocker:
    build:
      context: ./knocker
    privileged: true

  openconnect:
    build:
      context: ./openconnect
    ports:
      - "4443:443"
    privileged: true
    volumes:
      - ./users.txt:/etc/ocserv/users.txt

