#!/bin/bash

#usage $0 client_ip docker_vpn_port 
client_ip=$1
vpn_port=$2

#Allow port for forwarding
iptables -A INPUT -p tcp -s ${client_ip}  --dport ${vpn_port} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport ${vpn_port} -m conntrack --ctstate ESTABLISHED -j ACCEPT

#forwarding port
iptables -t nat -A PREROUTING -p tcp -s ${client_ip} --dport 443 -j REDIRECT --to-port ${vpn_port}
